# Exclude CNF, cnf, and iec files
exclude: '(?:\.cnf|\.CNF|\.iec)$'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-ast
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: name-tests-test
        exclude: tests/utils.py
      - id: pretty-format-json
        exclude_types: [jupyter]
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        args: [
            "--ignore-words-list=livetime,livetimes,Te,te,Nb,nd,FOM,fom",
            '--ignore-regex=^\s*"image\/png":\s.*', # ignore jupyter notebook images
          ]
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint-fix
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.8.5
    hooks:
      - id: nbqa-check-ast
        additional_dependencies: [pre-commit-hooks]
        args: [--nbqa-dont-skip-bad-cells]
      - id: nbqa-pyupgrade
        additional_dependencies: [pyupgrade==v3.15.0]
        args: [--py37-plus]
      - id: nbqa-isort
        additional_dependencies: [isort==5.13.2]
        args: [--profile=black, --float-to-top]
      - id: nbqa-black
        additional_dependencies: [black==24.1.1]
      - id: nbqa-pydocstyle
        additional_dependencies: [pydocstyle==6.3.0]
        args: ["--ignore=D100,D103"]
      - id: nbqa-flake8
        additional_dependencies: [flake8==7.0.0, flake8-bugbear]
        args: [--max-line-length=88, "--ignore=E203,E722,F821,W503,B001,B015"]
